In [1]:
import numpy as np

In [2]:
mylist = [1,2,3,4,5,6,7,8,9]
arr = np.array(mylist)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(9,)

In [6]:
arr.size

9

In [7]:
##Multidimensional Array

mylist1 = [1,2,3,4,5]
mylist2 = [2,3,4,5,6]
mylist3 = [3,4,5,6,7]

In [8]:
arr1 = np.array([mylist1, mylist2, mylist3])

In [9]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [10]:
arr1.shape

(3, 5)

In [11]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [12]:
##Indexing

arr[3]

4

In [13]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [14]:
arr1[0:,:3]

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [19]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [25]:
##Copy and Broadcast data

arr[3:]=200

In [26]:
arr

array([  0,   1,   2, 200, 200, 200, 200, 200, 200, 200])

In [27]:
arr3=arr.copy()

In [28]:
print(arr)
arr3[3:]=300
print(arr3)

[  0   1   2 200 200 200 200 200 200 200]
[  0   1   2 300 300 300 300 300 300 300]


In [30]:
#Conditions used in EDA

val = 3

arr[arr<val]

array([0, 1, 2])

In [31]:
arr<val

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [32]:
arr*3

array([  0,   3,   6, 600, 600, 600, 600, 600, 600, 600])

In [35]:
##Random Distribution

np.random.rand(3,3)

array([[0.92270131, 0.11206261, 0.31640007],
       [0.13858181, 0.20785905, 0.94308095],
       [0.33987452, 0.62260351, 0.63721451]])

In [36]:
np.random.randn(3,3)

array([[-1.08352632, -0.14239902,  0.2680409 ],
       [-0.35240276,  0.44652135,  0.84400265],
       [-0.39574307, -0.84209832,  0.48025652]])

In [37]:
np.random.random_sample((3,3))

array([[0.78446976, 0.47485939, 0.15729829],
       [0.51118253, 0.22076032, 0.22761391],
       [0.43133363, 0.71395292, 0.43223172]])